export const SET_LEADERS = 'SET_LEADERS';
export const UPDATE_LEADER_PAGINATION = 'UPDATE_LEADER_PAGINATION';
export const SET_EXPERTS = 'SET_EXPERTS';
export const UPDATE_EXPERT_PAGINATION = 'UPDATE_EXPERT_PAGINATION';
